name: Continuous Integration

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Continuous Integration
    uses: Joe-Hille-InContact/zero-to-hero-JH/.github/workflows/reusable-build.yml@zero-to-hero
    with:
      dotnet_version: 9.0.x