name: PR Verify

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: PR Verify
    uses: Joe-Hille-InContact/zero-to-hero-JH/.github/workflows/reusable-build.yml@zero-to-hero
    with:
      dotnet_version: 9.0.x